### ISSUE TITLE
test m with no ceiling

### ISSUE THREAD

**Issue by vakowal** [vakowal/sda-regional-pathways#28]
calculate SDA pathways using a version of m that includes no ceiling. does this have an impact on pathways for any regions?

**Comment by e-feth** [comment]
Faceted plot added to figures folder. Surprisingly, no cap does have an impact on cumulative emissions in some scenarios. Will be interesting to see what could be causing this - is this happening only in scenarios with reductions in floor area over time?

**Comment by vakowal** [comment]
I think this is done! see PR #35 and PR #36
