### ISSUE TITLE
Calculate empirical intensity pathways and compare to SDA intensity pathways

### ISSUE THREAD

**Issue by vakowal** [vakowal/sda-regional-pathways#3]
Calculate intensity pathways from empirical emissions and activity pathways. Compare these to pathways calculated from SDA.

**Comment by vakowal** [comment]
My idea is that we should plot the pathways together - one line for the empirical pathway, one line for SDA pathway. One plot per region / scenario combination.

**Comment by e-feth** [comment]
Sounds like a good plan re comparison of two lines in one plot for each region/scenario combo!

**Comment by e-feth** [comment]
Plots came out as expected for normative IPCC models, but produced some mixed/weird results for references that show bottom-up/country-level pathways.  Pushed IPCC plots to main branch,  still working on how to handle country-level plots. Not sure if it even makes sense to compare regional pathways to single country level pathways?
