### ISSUE TITLE
Test out alternative m parameter calculations

### ISSUE THREAD

**Issue by vakowal** [vakowal/sda-regional-pathways#4]
Try out a few different ways of calculating the m parameter.
Options that have been floated in meetings up to this point:

- cap/restrict bottom and top values of m?
- Add a multiplier / constant that weakens m? (what would this constant depend on? Maybe nothing, maybe it’s arbitrarily applied according to our judgment)
- M is always 1

Things to evaluate with the different versions:
 - is global carbon budget preserved?
 - are some countries unfairly disadvantaged?
 - how does the resulting pathway compare to empirical pathways or other sources?

**Comment by e-feth** [comment]
I think for this week, we should focus on capping m and setting m equal to 1. Results from those tests can help shape our decision making about a constant that could weaken m

**Comment by vakowal** [comment]
this is done, for now, with [b943baa](https://github.com/vakowal/sda-regional-pathways/commit/b943baad666085b13888e752d92ed2b6f8f8153f)
